DECLARE @COLUMN_NAME VARCHAR(100) = 'MEMBER_ID'
DECLARE @TABLE_NAME VARCHAR(100) = 'US'

    SELECT TBL.NAME AS TABLE_NAME
         , COL.NAME AS COLUMN_NAME
         , COL.MAX_LENGTH AS COLUMN_MAX_LENGTH
         , IIF(COL.IS_NULLABLE = 1, 'TRUE', 'FALSE') AS COLUMN_NULLABLE
         , TBL.CREATE_DATE AS TABLE_CREATE_DATE
         , TBL.MODIFY_DATE AS TABLE_MODIFY_DATE
      FROM SYS.TABLES AS TBL
INNER JOIN SYS.COLUMNS AS COL ON TBL.OBJECT_ID = COL.OBJECT_ID
     WHERE COL.NAME LIKE CONCAT('%', @COLUMN_NAME, '%')
       AND TBL.NAME LIKE CONCAT('%', @TABLE_NAME, '%')
  ORDER BY TBL.NAME
