DECLARE @NOW DATETIME = GETDATE()

DECLARE @TODAY VARCHAR(10) = CONVERT(DATE, GETDATE()) -- 2022-08-04
@TODAY = CONVERT(VARCHAR(10), GETDATE(), 121) -- 2022-08-04

DECLARE @TEMP TABLE(
  NAME VARCHAR(10)
)
INSERT INTO @TEMP ( NAME )
(
  SELECT 'A' AS NAME UNION ALL
  SELECT 'B' AS NAME UNION ALL
  SELECT 'C' AS NAME UNION ALL
  SELECT 'D' AS NAME UNION ALL
  SELECT 'E' AS NAME UNION ALL
  SELECT 'F' AS NAME
)
SELECT NAME FROM TEMP
/*
  A
  B
  C
  D
  E
  F
*/
