DECLARE @TABLE_NAME VARCHAR(10) = 'MEMBER'
DECLARE @DATA_TYPE VARCHAR(10) = ''

SELECT COL.ORDINAL_POSITION
     , COL.COLUMN_NAME
     , COL.DATA_TYPE
     , IIF ( ( SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = @TABLE_NAME AND COLUMN_NAME = COL.COLUMN_NAME ) > 0, 'TRUE', 'FALSE' ) AS IS_KEY
     , COL.COLUMN_DEFAULT
     , COL.CHARACTER_MAXIMUM_LENGTH
     , COL.IS_NULLABLE
  FROM INFORMATION_SCHEMA.COLUMNS AS COL
 WHERE TABLE_NAME = @TABLE_NAME
   AND DATA_TYPE LIKE CONCAT('%', @DATA_TYPE, '%' )
